CREATE SCHEMA ACME;

CREATE TABLE ACME.EMPLOYEE (
E_ID VARCHAR(8) NOT null PRIMARY KEY,
E_FIRST_NAME VARCHAR(32),
E_LAST_NAME VARCHAR (32),
E_ADDRESS VARCHAR(256)
);

CREATE SCHEMA ACMEDB;

CREATE TABLE ACMEDB.CUSTOMER (
C_ID VARCHAR (8) NOT null PRIMARY KEY,
C_FIRST_NAME VARCHAR(32),
C_LAST_NAME VARCHAR (32),
C_ADDRESS VARCHAR(256),
C_PASSWORD VARCHAR(64)
);

CREATE TABLE ACMEDB.SAVINGS (
C_ID VARCHAR (8),
/*FOREIGN KEY (C_ID) REFERENCES ACMEDB.CUSTOMER(C_ID),*/
C_ACCOUNT_NUMBER INTEGER,
C_BALANCE INTEGER
);

CREATE SCHEMA ACMEJMS;
/*
CREATE TABLE ACMEJMS.HOMELOAN (
C_ID VARCHAR (8),
FOREIGN KEY (C_ID) REFERENCES ACMEDB.CUSTOMER(C_ID),
C_FULL_NAME VARCHAR (128),
C_FULL_ADDRESS VARCHAR (128),
C_ACCOUNT_NUMBER INTEGER,
C_AMOUNT_DEBIT INTEGER,
C_AMOUNT_CREDIT INTEGER,
C_DOB DATE,
C_JOB VARCHAR (64),
C_SALARY INTEGER,
C_EMAIL VARCHAR (64),
C_PHONE INTEGER
);
DROP TABLE ACME.EMPLOYEE;
DROP TABLE ACMEDB.CUSTOMER;
DROP TABLE ACMEDB.SAVINGS;
DROP TABLE ACMEJMS.HOMELOAN;
DROP SCHEMA ACME RESTRICT;
DROP SCHEMA ACMEBD RESTRICT;

